### ISSUE TITLE
The result of count_distinct() is wrong

### ISSUE THREAD

**Issue by zhangy5** [apache/incubator-doris#1553]
**Describe the bug**
The result of count_distinct() is wrong. The count_distinct result is different from count distinct.
![count_distinct](https://user-images.githubusercontent.com/10826066/61928709-e2273700-afab-11e9-8edf-7b6e1d03b005.png)

Column k1 is tinyint type, the result of count distinct should be less than 256.

Create table like :
CREATE TABLE `test` (
  `k1` tinyint(4) NOT NULL COMMENT "",
  `k2` smallint(6) NOT NULL COMMENT "",
  `k3` int(11) NOT NULL COMMENT "",
  `k4` bigint(20) NOT NULL COMMENT "",
  `k5` decimal(9, 3) NOT NULL COMMENT "",
  `k6` char(5) NOT NULL COMMENT "",
  `k10` date NOT NULL COMMENT "",
  `k11` datetime NOT NULL COMMENT "",
  `k7` varchar(20) NOT NULL COMMENT "",
  `k8` double MAX NOT NULL COMMENT "",
  `k9` float SUM NOT NULL COMMENT ""
) ENGINE=OLAP
AGGREGATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`, `k6`, `k10`, `k11`, `k7`)
PARTITION BY RANGE(`k1`)
(PARTITION placeholder_0 VALUES LESS THAN ("-128"),
PARTITION p1 VALUES LESS THAN ("-64"),
PARTITION p2 VALUES LESS THAN ("0"),
PARTITION p3 VALUES LESS THAN ("64"),
PARTITION p4 VALUES LESS THAN MAXVALUE)
DISTRIBUTED BY HASH(`k1`) BUCKETS 5
PROPERTIES (
"storage_type" = "COLUMN"
);

**Comment by lordk911** [comment]
+1

**Comment by xy720** [comment]
work in progress

**Comment by xy720** [comment]
Now the `count_distinct()` is with the same symbol as `count()` function, which means that `count_distinct()` run as the same code as `count()` function.  That's why the above mistakes happen.
Besides, we already have function `multi_distinct_count()` as an alternative to help us calculate "count distinct" of any type value.
So we don't need `count_distinct()` anymore, we should remove this function.

现在`count_distinct()`与`count()`函数具有相同的函数签名，这意味着`count_distinct()`与`count()`函数在后台以相同的代码运行，这就是为什么会发生上述错误。
此外，我们已经有了函数`multi_distinct_count()`来帮助我们计算任何类型值的"count distinct"值。
所以我们不再需要`count_distinct()`，建议删除这个函数。

**Comment by zhangy5** [comment]
Please update help doc.
docs/documentation/cn/sql-reference/sql-functions/aggregate-functions/count_distinct.md
