### ISSUE TITLE
support filter with predicate in BetaRowset

### ISSUE THREAD

**Issue by imay** [apache/incubator-doris#1652]
Support predicate filter in BetaRowset iterator.

It's better if we can support lazy materialization.

**Comment by gaodayue** [comment]
If you mean filter rows by columns's zonemap, it's already supported

**Comment by imay** [comment]
@gaodayue 
> If you mean filter rows by columns's zonemap, it's already supported

I mean that vectorized predicate filter. In AlphaRowset, this logic locates in ColumnData, we should support it in SegmentIterator to filter data as soon as possible.

**Comment by gaodayue** [comment]
I see, thanks

**Comment by kangpinghuang** [comment]
I will do this feature

**Comment by kangpinghuang** [comment]
I will split this job into several step:
1. I will move original v1's predicate logic to segment v2 to provide this feature quickly.
2. I will refactor the current column predicate framework because current column predicate is based on row block. I will modify it to calculate based on column cell. This work wil be the base of the following work.
3. I will realize lazy materiazation to optimize data read.
4. I will realize the optimization to push predicate evalution to page decoder which will optimize in some situation, eg: dict encoded page.

**Comment by EmmyMiao87** [comment]
#1775
