### ISSUE TITLE
Support specifying inverted index columns when creating table for segment V2

### ISSUE THREAD

**Issue by wubiaoi** [apache/incubator-doris#1865]
like bloom filter:
```
CREATE TABLE example_db.table_hash
        (
        k1 TINYINT,
        k2 DECIMAL(10, 2) DEFAULT "10.5",
        v1 CHAR(10) REPLACE,
        v2 INT SUM
        )
        ENGINE=olap
        AGGREGATE KEY(k1, k2)
        DISTRIBUTED BY HASH(k1) BUCKETS 32
        PROPERTIES 
        (
            "storage_type"="column"，
            "inverted_index_columns" = "k1,k2"
        );
```

**Comment by wubiaoi** [comment]
For #1684

**Comment by imay** [comment]
@wubiaoi 

First, I'm very sorry to reply so late that your PR has been commit.
I have some question about this interface. 

1. Why not we use the syntax like MySQL do? Now you put "inverted_index_columns" in properties, if we add some more options to it, it will be more difficult to parse and difficult to user to use it. Such as we support more index type, and more options for each type of index, or we support index multiple columns in one index.
2. You should propose `CREATE INDEX` and `DROP INDEX` syntax together. Because some of indices are created when they are needed. And then we should have an index name for each index, however if we create index in your way, user don't know index name explicitly.

**Comment by wubiaoi** [comment]
> @wubiaoi
> 
> First, I'm very sorry to reply so late that your PR has been commit.
> I have some question about this interface.
> 
> 1. Why not we use the syntax like MySQL do? Now you put "inverted_index_columns" in properties, if we add some more options to it, it will be more difficult to parse and difficult to user to use it. Such as we support more index type, and more options for each type of index, or we support index multiple columns in one index.
> 2. You should propose `CREATE INDEX` and `DROP INDEX` syntax together. Because some of indices are created when they are needed. And then we should have an index name for each index, however if we create index in your way, user don't know index name explicitly.

@imay Yeah, `CREATE INDEX` and `DROP INDEX` will be supported later.

**Comment by morningman** [comment]
it has been implement in another pr. #2573
