### ISSUE TITLE
BE crash when loading 

### ISSUE THREAD

**Issue by morningman** [apache/incubator-doris#1984]
**Describe the bug**
BE crashed when deconstructing mem tracker in memtable when doing loading process.

** Why **
Because the parent mem tracker in load channel has been destroyed before deconstructing
memtable. So that when deconstructing memtable, the visit of its parent mem tracker cause 
segment fault.

** How to resolve**
Release the memtable before notifying the load channel, so that the parent mem tracker 
in load channel will remain alive.

**Comment by gaodayue** [comment]
I think the issue still exists after #1983 because `FlushHandle::wait` can return early due to `CounterCondVariable::dec_to_zero` when one memtable failed to flush or is cancelled. So when a DeltaWriter has several memtables in the flush queue and the first memtable causes `FlushHandle::wait` to return, DeltaWriter could have been deallocated when latter memtables are accessed.
