### ISSUE TITLE
Compressor comparison of segment v1 and segment v2

### ISSUE THREAD

**Issue by zhangy5** [apache/incubator-doris#2086]
I compared the string compressor of segment v1 and segment v2. The result is.
![image](https://user-images.githubusercontent.com/10826066/67676780-426bb180-f9bd-11e9-9589-7be2d94dcf24.png)

1. The table schema has only one string column.
2. There are total 10e9 characters random generated in file except separator. If column type is char(1), there are 10e9 rows of data. If column type is char(10), there are 10e8 rows of data.
3. Load data, then show data. 
version: 189e08faa59963d40f99a4aeb140ee6f326131ac

**Comment by imay** [comment]
@zhangy5 
For random string, V2 is the same with V1, because the dictionary is useless.
Could you please test with some non random value?
In many cases, the string field content is like region, country. In this case dictionary will be very helpful.

You can add a parameter in your test to control the cardinality of your generated string.

**Comment by zhangy5** [comment]
OK，I will add some non random value. char1 is actually a fixed set. 
But the result of segment v2 is still a little strange. The char10 is too much big and char65535 load job is failed.

**Comment by imay** [comment]
> OK，I will add some non random value. char1 is actually a fixed set.
> But the result of segment v2 is still a little strange. The char10 is too much big and char65535 load job is failed.

Yeah, for this problem you should create another issue to track it.

**Comment by zhangy5** [comment]
Test with new data, the result as follows. 
![image](https://user-images.githubusercontent.com/10826066/67764694-7ad6c280-fa85-11e9-8c36-7b1ced00ee5b.png)

1. the table schema is char(100), only one column
2. test with different cardinality

**Comment by kangpinghuang** [comment]
I have analyse the two problems of this test.
1. char65535 load job is failed. This is becasue there is max_body_size limit for brpc message. The batch sent  between BE for char65535 when loading data is too large which lead to failure when rpc. This can be fixed by limit the batch size under the max_body_size or set brpc_max_body_size to a bigger number in BE.
2. char10 is too big. The reason is that the dict page's size limit is default to 1M and the dict is too large, DictEncoding automatically switch to BinaryPlainEncoding. BinaryPlainEncoding is less effiecient than V1. I will optimize the PlainEncoding later.
