### ISSUE TITLE
'nan'  result didn't merge

### ISSUE THREAD

**Issue by manannan2017** [apache/incubator-doris#2142]
1、table
![image](https://user-images.githubusercontent.com/33174388/68280820-49777b80-00b1-11ea-92be-822aa4f88964.png)

![image](https://user-images.githubusercontent.com/33174388/68280903-76c42980-00b1-11ea-86d2-c4950c652ae9.png)

![image](https://user-images.githubusercontent.com/33174388/68281343-71b3aa00-00b2-11ea-8cdc-814cb326411e.png)

sql： DECIMAL + char
 select k6 + k5 as nu from test group by nu;

2、excepted result：
‘nan’  result can merge

**Comment by yangzhg** [comment]
i will fix it

**Comment by yangzhg** [comment]
这个现象的原因是在 be 和fe 的代码中我们对于 数字和字符串的算数运算处理逻辑导致的，在字符串和数字做算数运算时 字符串会默认cast 成 double 类型。不同的数据库对于这个问题的处理也不同，比如postgres 不支持这种操作，mysql 支持，mysql 的逻辑是匹配字符串前缀 转换成数字，前缀没有数字则是0 比如 `1 + '1' = 2`, `1 + '1a' = 2` , `1 + 'a' = 1` , `1 + 'a1' = 2` , 我们部分兼容了mysql 的操作，但是字符串转数字 只支持完整的字符串格式， 和类似NAN 这种 其他情况会 报错， 使整个表达式值变为 null，例如  `1 + '1' = 2`， `1 + '1a' = null`  `1 + 'nan' = nan` 具体细节见代码  `be/src/util/string_parser.hpp`, 
但是现在 由于doris 有一定的用户量，所以无论是改成 mysql 兼容还是 postgres 兼容 都会引起对现在的已有用户的不兼容现象，因此 这个问题暂时保持现状，不做处理，等待以后在处理


The reason for this case is that in the code of be and fe, our logic of arithmetic operation for  numbers and strings is caused. When performing arithmetic operations on strings and numbers, strings are cast to double by default. Different databases deal with this problem differently. For example, postgres does not support this operation. MySQL supports it. The logic of mysql is to match the string prefix to a number. If the prefix is not a number, it is 0. For example, 1 + '1' = 2, 1 + '1a' = 2, 1 + 'a' = 1, 1 + 'a1' = 2, we are partially compatible with mysql operations, but string to number only supports the full string format, and other similar to NAN and other The situation will report an error, making the entire expression value null, such as 1 + '1' = 2, 1 + '1a' = null 1 + 'nan' = nan. For details, see the code be / src / util / string_parser.hpp,
But now that doris has a certain number of users, no matter whether it is mysql compatible or postgres compatible, it will cause incompatibility to existing users. Therefore, this issue will remain the status quo for the time being, do not deal with it, and wait for the future

**Comment by yangzhg** [comment]
这个问题的原因是在 be 和fe 的代码中我们对于数字和字符串的算数运算处理逻辑导致的，在字符串和数字做算数运算时 字符串会默认cast 成 double 类型。不同的数据库对于这个问题的处理也不同，比如postgres 不支持这种操作，mysql 支持，mysql 的逻辑是匹配字符串前缀 转换成数字，前缀没有数字则是0 比如 `1 + '1' = 2`, `1 + '1a' = 2` , `1 + 'a' = 1` , `1 + 'a1' = 2` , 我们目前的代码部分兼容了mysql 的操作，但是字符串转数字只支持完整的字符串格式和类似NAN/INF这种形式，其他情况会报错， 使整个表达式值变为 null，例如  `1 + '1' = 2`， `1 + '1a' = null`  `1 + 'nan' = nan` 具体细节见代码  `be/src/util/string_parser.hpp`, 但是我们的代码似乎错用了string_parser.hpp， string_parser 的实际行为是和mysql 保持一致的， 只是在parse的状态上有 对于 完全是字符串的情况 会返回一个错误状态码，但是有默认值0返回，相反的对于NAN 和 INF 我们代码却没有对应的处理逻辑，应该返回NULL， 所以这个问题可以看成是doris 对于这种情况的一种错误处理
但是现在 由于doris 有一定的用户量，所以无论是改成 mysql 兼容还是 postgres 兼容 都会引起对现在的已有用户的不兼容现象，因此 这个问题可以暂时保持现状，等待以后在处理， 也可以修复这个错误的处理逻辑，因为对于使用了group by 的用户可能出现错误的结果

The reason for this problem is that in the code of be and fe, our arithmetic operation logic for numbers and strings is caused. When performing arithmetic operations on strings and numbers, strings are cast to double by default. Different databases deal with this problem differently. For example, postgres does not support this operation. MySQL supports it. The logic of mysql is to match the string prefix to a number. If the prefix is ​​not a number, it is 0. For example, `1 + '1' = 2` , `1 + '1a' = 2`,` 1 + 'a' = 1`, `1 + 'a1' = 2`, our current code is partially compatible with mysql operations, but string to number support only complete String format and forms like NAN / INF, other cases will report errors, making the entire expression value null, such as `1 + '1' = 2`,` 1 + '1a' = null` `1 + 'nan' = nan` For details, see the code `be / src / util / string_parser.hpp`, but our code seems to use string_parser.hpp incorrectly. The actual behavior of string_parser is consistent with mysql, only in the parse state There is an error status code for a completely string case, but a default value of 0 is returned. In contrast, for NAN and INF, our code has no corresponding processing logic and should return NULL, so this problem can be seen as doris An error handling for this situation
But now that doris has a certain number of users, whether it is mysql-compatible or postgres-compatible will cause incompatibility to existing users. Therefore, this problem can be temporarily maintained, waiting to be processed later, or you can fix this. Wrong processing logic, because users who use group by may have wrong results
