### ISSUE TITLE
【sql mode】when broker load data，the result is NULL  except for the first line

### ISSUE THREAD

**Issue by manannan2017** [apache/incubator-doris#2428]
1、table：

2、set sql_mode = “PIPES_AS_CONCAT”
 1> the origin data:
![image](https://user-images.githubusercontent.com/33174388/70600802-99ef7500-1c2b-11ea-8cd0-36c72f6a327b.png)

2>broker load sql(include || operator):
INTO TABLE tb COLUMNS TERMINATED BY "\t" (`v1`, `v2`, `v3`, `v4`, `v5`, `v6`, `v10`, `v11`, `v7`, `v8`, `v9`) SET(k1=(v1 || 10),** k2=(v2), k3=v3, k4=v4, k5=v5, k6=nullif(v6, "false"), k7=v7, k10=v10, k11=v11, k8=v8, k9=v9)) WITH BROKER "hdfs" (...)

3> the result ()is :
![image](https://user-images.githubusercontent.com/33174388/70600997-1b470780-1c2c-11ea-9641-a75b0f95f94c.png)

4> excepetd:
![image](https://user-images.githubusercontent.com/33174388/70601184-7a0c8100-1c2c-11ea-9633-855320a66815.png)

#2252

**Comment by xy720** [comment]
This is because the loaded K1 string exceeds the range of TINYINT after being converted to a number, which makes the final value of K1 to null. As long as we make K1 = (V1 || 10) chang to K1 = (V1 || 1), the loaded K1 won't be null.
When the nullable property of K1 is false, if the loaded K1 string converted to a number exceeds the range of TINYINT, the load job will report an error, but in this case, the nullable property of K1 is true, so there is no error reported.

这是因为导入的k1字符串转为数字后超过了tinyInt的范围，才使得k1最后的值为null，只要将k1 = (v1 || 10) 改成 k1 = (v1 || 1)，导入k1就不会出现null了。
当k1的nullable属性为false时，若导入的k1字符串转为数字后超过了tinyInt的范围，loadJob将会报错，但是在本case中k1的nullable属性为true，因此没有报错。
