### ISSUE TITLE
Boost error upon cloning tablet

### ISSUE THREAD

**Issue by chaoyli** [apache/incubator-doris#2465]
cloning tablet throw boost exception
```
W1216 15:33:31.593262  5451 utils.cpp:89] agent clinet make snapshot, get exception, error: boost::filesystem::current_path: No such file or directory
```
all cloning tablet is stalled.

**Comment by Seaven** [comment]
The problem may be caused by snapshot_manager create tablet directory error, then use the error path will throw exception. The exception maybe threw by line: 339, but can't sure the reason if haven't other log.

So, the problem maybe will replay, and we have add logs when file operator error in later version, need to follow up the problem.
