### ISSUE TITLE
[Proposal] Select * support HLL and Bitmap column

### ISSUE THREAD

**Issue by kangkaisen** [apache/incubator-doris#2976]
## Why
Currently, select * doesn't support HLL and Bitmap column.
1. Which isn't compatible with tableau or navicat ... mysql tool and BI tools.
2. Which isn't friendly for user.

![image](https://user-images.githubusercontent.com/9894906/75128471-3095e300-56ff-11ea-9523-f0a7a7822d75.png)
![image](https://user-images.githubusercontent.com/9894906/75128477-37bcf100-56ff-11ea-9431-8b9ea5012a37.png)

## How
1. return null for  HLL and Bitmap column when select *

2. Directly return HLL and bitmap binary content when select *

3. Rewrite the sql and return cardinality of HLL or bitmap when select *

4. Rewrite the sql and return to_string of HLL or bitmap when select *

I prefer to solution 3:  **Rewrite the sql and return cardinality of HLL or bitmap when select**

**Comment by imay** [comment]
I prefer 2.
If we follow the third way, its behavior will be inconsistent with `insert into select *`.

**Comment by gaodayue** [comment]
Usually it's a mistake to directly select HLL or bitmap column without applying function on it. In order to work around the "select *" queries issued automatically by BI tools, we could return NULL for HLL and bitmap columns by default. For users who want to get the raw binary of HLL and bitmap, we could add a configuration like `return_raw_value_for_complex_type` to support such scenario.

**Comment by kangkaisen** [comment]
> For users who want to get the raw binary of HLL and bitmap, we could add a configuration like `return_raw_value_for_complex_type` to support such scenario.

We don't need a configuration, If users indeed want to get the raw binary of HLL and bitmap, they could use `select hll_column, bitmap_cilumn from table`.  which sql is valid in Doris.
