### ISSUE TITLE
FE Bdbje file size has been increased to 37G, Why not merge?

### ISSUE THREAD

**Issue by leijian** [apache/incubator-doris#312]
**Describe Problems**
1. FE Bdbje file size has been increased to 37G, no warning. Why not merge bdbje journal log?
2. Forgotten to copy the bdjb file during cluster migration, the error message is not clear in BE and FE log.

**Runtime Statistic**
- Palo FE:  3 instances(CPU-8core, JVM Memory-4GB, System Memory-15GB, Disk-100GB)
- Palo BE:  19 instances(CPU-16core, Memory-32GB, Disk-1TB)
- Load Jobs TPS:  20/minute MiniLoad
- Total Jobs: 2W+ MiniLoad
- Data Statistic: 25 Table，300+ Partition，4000+ Tablet，12000+ Replica,  3TB Total Size

**Additional context**
- Palo Version: 0.8.0
- Linux Version: CentOS 7.3.1611
- Doris-BE&FE Running on Docker Version:  1.6.2

**Comment by morningman** [comment]
1. The FE bdbje file size issue is described here: 
https://github.com/apache/incubator-doris/wiki/Doris-Metadata-Operation-Guide#%E5%85%B6%E4%BB%96%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

You can follow this wiki to find the reason.

2. Forgotten to copy the bdjb file.

I think this is human operation mistake that can not be guaranteed by Doris itself.
Because Doris is truly support only use image file to start the cluster.
So Doris can not differentiate the situations of "BDBJE DIR IS MISSING" and "BDBJE DIR DOES NOT EXIST"
