### ISSUE TITLE
[Doris on ES] unix_timestamp(date_format(now(), '%Y-%m-%d')) not push down

### ISSUE THREAD

**Issue by BabySid** [apache/incubator-doris#3559]
**Describe the bug**

I found a slow query:
```
select k1 from mytable where Updatetime < unix_timestamp(date_format(now(), '%Y-%m-%d')) ;
```
It costs more than 5s.

The log in be.INFO is
```
{"query":{"match_all":{}},"stored_fields":"_none_","docvalue_fields":["k1","UpdateTime"],"sort":["_doc"],"size":4096}
```

i used another sql with the same meaning:
```
select k1 from mytable where Updatetime < 1589212800;
```
it costs less then 1s.

The log in be.INFO is
```
 {"query":{"bool":{"filter":[{"bool":{"should":[{"range":{"UpdateTime":{"lt":"1589212800"}}}]}}]}},"stored_fields":"_none_","docvalue_fields":["k1","UpdateTime"],"sort":["_doc"],"size":4096}
```

I suspect that these basic functions (e.g. unix_timestamp(date_format(now(), '%Y-%m-%d'))) are not precomputed. 

**Version: Master**

**Comment by wuyunfeng** [comment]
emm...

**Comment by wuyunfeng** [comment]
@blackfox1983 
I think maybe the reason maybe is Data-Type is different with  unix_timestamp(date_format(now(), '%Y-%m-%d')),
I just create a table:

```

CREATE EXTERNAL TABLE `fucntion_push` (
  `k1` bigint COMMENT "",
   `k2`  date COMMENT ""
) ENGINE=ELASTICSEARCH
```
create a mapped index in es:

```
PUT function_push
{
   "settings": {
      "index": {
         "number_of_shards": "1",
         "number_of_replicas": "0"
      }
   },
   "mappings": {
      "doc": {
         "properties": {
            "k1": {
               "type": "long"
            },
            "k2": {
               "type": "date"
            }
         }
      }
   }
}
```

explain this SQL:

![image](https://user-images.githubusercontent.com/5183061/84991263-dec70c00-b178-11ea-95fc-e74deb56a454.png)

As we can see date_format(now(), '%Y-%m-%d') can be pre-computed by Doris FE, but because `k1` datatype is different with the returned type `unix_timestamp`, all these two `Expr` become `CastExpr`.

**Comment by wuyunfeng** [comment]
BTW, it seems Doris can not rewrite nested function:

![image](https://user-images.githubusercontent.com/5183061/84992495-8db81780-b17a-11ea-8c37-cda6cbaeb8ef.png)
