### ISSUE TITLE
[BUG] retry submit exception is not catched

### ISSUE THREAD

**Issue by xinghuayu007** [apache/incubator-doris#4795]
**Describe the bug**
When `Load Job Task Queue` is filled, continue to submit more jobs to the queue will cause `RejectedExecutionException`, and the load job will be retried. But `callback.onTaskFailed` function does not catch the exception, that will cause re-submitting job failed, and status is not updated to failed.

**To Reproduce**
1. set FE configuration: async_load_task_pool_size=30
2. create a table
3. create more than 60 broker load jobs, start them concurrently to fill the broker load job queue.
![2020-10-26 19-46-31屏幕截图](https://user-images.githubusercontent.com/12771191/97180171-b01b0b00-17d4-11eb-9c6b-8d592a6b52dc.png)
![2020-10-26 19-46-49屏幕截图](https://user-images.githubusercontent.com/12771191/97180186-b3ae9200-17d4-11eb-9081-d2d7095148e5.png)
the status of job is not updated to failed.
![2020-10-26 21-48-50屏幕截图](https://user-images.githubusercontent.com/12771191/97180499-1b64dd00-17d5-11eb-97ab-9996c90881a7.png)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by EmmyMiao87** [comment]
Another problem is that I think loading should not have so much concurrency control. 
In fact, db itself already has a control of the number of transactions. 
So the number of concurrent tasks here is best to be twice the number of transactions. 

Also, if the submitted task is abnormal, I think the load job can be cancelled directly.
The reason is that after the system is currently loading the stack, it is generally difficult to recover quickly, so you are not sure how long you will have to wait to retry successfully.
