### ISSUE TITLE
[Proposal] Disable v1 storage format when creating a new table in version 0.14

### ISSUE THREAD

**Issue by yangzhg** [apache/incubator-doris#4835]
At present, our V2 storage format has been developed for a long time, and V2 has many advantages that V1 does not have. The coexistence of V1 and V2 brings a lot of code and cluster maintenance costs.
Therefore, I think the next version, that is, version 0.14 will disable the use of V1 storage format for newly created tables.

**Comment by HappenLee** [comment]
good idea~

**Comment by hf200012** [comment]
good idea

**Comment by zhaojintaozhao** [comment]
Currently, many companies are using the v1 storage format. The v2 format is not stable yet. The new Doris version must be compatible with earlier versions. Therefore, I do not recommend disabling v1 storage format.

**Comment by blueChild** [comment]
Would it be better if we should allow users to choose which version to use instead of disabling it?

**Comment by zhaojintaozhao** [comment]
The right to choose the storage format v1 or  v2 should be delegated to the user.

**Comment by morningman** [comment]
Hi @zhaojintaozhao @blueChild 
SegmentV2 is implemented since v0.12, and has been online for a long time.
In v0.13, the default storage format has already been changed to SegmentV2, so that all **Newly Created** table
will use SegmentV2 as default. And all existed table has no effect.

What we discuss here is to disable V1 in v0.14, which is reasonable to me because you can think of 0.13 as a transitional version.

In addition, it is recommended to discuss this issue in the dev mail list(dev@doris.apache.org)
